on: push
name: Booking Portal
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm i -f
          npm run build
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Jest tests
        run: |
          npm test
      - name: Coverage report
        uses: codecov/codecov-action@v1

  cypress:
    runs-on: ubuntu-latest
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start                  # If your tests run against a local server, use start parameter, the server will run in the background and will shut down after tests complete
          wait-on: 'http://localhost:4200'  # you can add a parameter wait-on and pass url to wait for the server to respond.
  
      # - name: Prepare and deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     npm install
      #     npm run ng -- deploy --base-href=/booking-portal/ --name="LisaRomita" --email="lisa.romita@libero.it" --no-silent
  deploy:
    needs: [jest, cypress]
    runs-on: ubuntu-latest
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}