on: push
name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and npm run build
        run: |
          npm i -f
          npm run build
      - name: Jest tests
        run: |
          npx jest
      - name: Cypress tests
        run: |
          npm i cypress --save-dev
          npx cypress run
      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          tag: v1.2
          artifacts: "dist/booking-portal/*"
          token: ${{ secrets.TOKEN }}